clear -all

analyze -sv12 \
    +incdir+/home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/include \
    +incdir+/home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cluster_interconnect/rtl/low_latency_interco \
    +incdir+/home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cluster_interconnect/rtl/peripheral_interco \
    +incdir+/home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cluster_interconnect/../../rtl/includes \
    +incdir+/home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/adv_dbg_if/rtl \
    +incdir+/home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/apb/apb_adv_timer/./rtl \
    +incdir+/home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/axi/axi/include \
    +incdir+/home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/axi/axi/../../common_cells/include \
    +incdir+/home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/timer_unit/rtl \
    +incdir+/home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/fpnew/../common_cells/include \
    +incdir+/home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/jtag_pulp/../../rtl/includes \
    +incdir+/home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cv32e40p/./rtl/include \
    +incdir+/home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cv32e40p/./rtl/include \
    +incdir+/home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cv32e40p/../../rtl/includes \
    +incdir+/home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cv32e40p/./rtl/include \
    +incdir+/home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cv32e40p/tb/tb_riscv/include \
    +incdir+/home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cv32e40p/rtl/include \
    +incdir+/home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/ibex/rtl \
    +incdir+/home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/ibex/vendor/lowrisc_ip/ip/prim/rtl \
    +incdir+/home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma/udma_core/./rtl \
    +incdir+/home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma/udma_i2c/rtl \
    +incdir+/home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma/udma_qspi/rtl \
    +incdir+/home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/hwpe-ctrl/rtl \
    +incdir+/home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/hwpe-stream/rtl \
    +incdir+/home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/hwpe-mac-engine/rtl \
    +incdir+/home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/register_interface/include \
    +incdir+/home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/register_interface/../axi/axi/include \
    +incdir+/home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/register_interface/../common_cells/include \
    +incdir+/home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/register_interface/include \
    +incdir+/home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/register_interface/../axi/axi/include \
    +incdir+/home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/register_interface/../common_cells/include \
    +incdir+/home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/register_interface/include \
    +incdir+/home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/pulp_soc/../../rtl/includes \
    +incdir+/home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/pulp_soc/rtl/include \
    +incdir+/home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/pulp_soc/../axi/axi/include \
    +incdir+/home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/pulp_soc/../../rtl/includes \
    +incdir+/home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/pulp_soc/. \
    +incdir+/home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/pulp_soc/../../rtl/includes \
    +incdir+/home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/pulp_soc/. \
    +incdir+/home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/pulp_soc/../../rtl/includes \
    +incdir+/home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/pulp_soc/../../rtl/includes \
    +incdir+/home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/pulp_soc/../../rtl/includes \
    +incdir+/home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/rtl/includes \
    insn_add_ch0.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/binary_to_gray.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/cb_filter_pkg.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/cdc_2phase.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/cf_math_pkg.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/clk_div.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/delta_counter.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/ecc_pkg.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/edge_propagator_tx.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/exp_backoff.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/fifo_v3.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/gray_to_binary.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/isochronous_spill_register.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/lfsr.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/lfsr_16bit.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/lfsr_8bit.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/mv_filter.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/onehot_to_bin.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/plru_tree.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/popcount.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/rr_arb_tree.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/rstgen_bypass.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/serial_deglitch.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/shift_reg.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/spill_register.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/stream_demux.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/stream_filter.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/stream_fork.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/stream_intf.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/stream_join.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/stream_mux.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/sub_per_hash.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/sync.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/sync_wedge.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/unread.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/addr_decode.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/cb_filter.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/cdc_fifo_2phase.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/cdc_fifo_gray.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/counter.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/ecc_decode.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/ecc_encode.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/edge_detect.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/lzc.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/max_counter.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/rstgen.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/stream_delay.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/stream_fifo.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/stream_fork_dynamic.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/stream_xbar.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/fall_through_register.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/id_queue.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/stream_to_mem.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/stream_arbiter_flushable.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/stream_omega_net.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/stream_register.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/stream_arbiter.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/deprecated/clock_divider_counter.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/deprecated/find_first_one.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/deprecated/generic_LFSR_8bit.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/deprecated/generic_fifo.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/deprecated/generic_fifo_adv.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/deprecated/pulp_sync.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/deprecated/pulp_sync_wedge.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/deprecated/clock_divider.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/deprecated/fifo_v2.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/deprecated/prioarbiter.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/deprecated/rrarbiter.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/deprecated/fifo_v1.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/edge_propagator.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/common_cells/src/edge_propagator_rx.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/L2_tcdm_hybrid_interco/RTL/l2_tcdm_demux.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/L2_tcdm_hybrid_interco/RTL/lint_2_apb.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/L2_tcdm_hybrid_interco/RTL/lint_2_axi.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/L2_tcdm_hybrid_interco/RTL/axi_2_lint/axi64_2_lint32.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/L2_tcdm_hybrid_interco/RTL/axi_2_lint/axi_read_ctrl.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/L2_tcdm_hybrid_interco/RTL/axi_2_lint/axi_write_ctrl.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/L2_tcdm_hybrid_interco/RTL/axi_2_lint/lint64_to_32.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/L2_tcdm_hybrid_interco/RTL/XBAR_L2/AddressDecoder_Req_L2.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/L2_tcdm_hybrid_interco/RTL/XBAR_L2/AddressDecoder_Resp_L2.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/L2_tcdm_hybrid_interco/RTL/XBAR_L2/ArbitrationTree_L2.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/L2_tcdm_hybrid_interco/RTL/XBAR_L2/FanInPrimitive_Req_L2.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/L2_tcdm_hybrid_interco/RTL/XBAR_L2/FanInPrimitive_Resp_L2.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/L2_tcdm_hybrid_interco/RTL/XBAR_L2/MUX2_REQ_L2.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/L2_tcdm_hybrid_interco/RTL/XBAR_L2/RequestBlock_L2_1CH.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/L2_tcdm_hybrid_interco/RTL/XBAR_L2/RequestBlock_L2_2CH.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/L2_tcdm_hybrid_interco/RTL/XBAR_L2/ResponseBlock_L2.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/L2_tcdm_hybrid_interco/RTL/XBAR_L2/ResponseTree_L2.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/L2_tcdm_hybrid_interco/RTL/XBAR_L2/RR_Flag_Req_L2.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/L2_tcdm_hybrid_interco/RTL/XBAR_L2/XBAR_L2.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/L2_tcdm_hybrid_interco/RTL/XBAR_BRIDGE/AddressDecoder_Req_BRIDGE.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/L2_tcdm_hybrid_interco/RTL/XBAR_BRIDGE/AddressDecoder_Resp_BRIDGE.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/L2_tcdm_hybrid_interco/RTL/XBAR_BRIDGE/ArbitrationTree_BRIDGE.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/L2_tcdm_hybrid_interco/RTL/XBAR_BRIDGE/FanInPrimitive_Req_BRIDGE.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/L2_tcdm_hybrid_interco/RTL/XBAR_BRIDGE/FanInPrimitive_Resp_BRIDGE.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/L2_tcdm_hybrid_interco/RTL/XBAR_BRIDGE/MUX2_REQ_BRIDGE.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/L2_tcdm_hybrid_interco/RTL/XBAR_BRIDGE/RequestBlock1CH_BRIDGE.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/L2_tcdm_hybrid_interco/RTL/XBAR_BRIDGE/RequestBlock2CH_BRIDGE.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/L2_tcdm_hybrid_interco/RTL/XBAR_BRIDGE/ResponseBlock_BRIDGE.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/L2_tcdm_hybrid_interco/RTL/XBAR_BRIDGE/ResponseTree_BRIDGE.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/L2_tcdm_hybrid_interco/RTL/XBAR_BRIDGE/RR_Flag_Req_BRIDGE.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/L2_tcdm_hybrid_interco/RTL/XBAR_BRIDGE/XBAR_BRIDGE.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cluster_interconnect/rtl/low_latency_interco/FanInPrimitive_Req.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cluster_interconnect/rtl/low_latency_interco/ArbitrationTree.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cluster_interconnect/rtl/low_latency_interco/MUX2_REQ.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cluster_interconnect/rtl/low_latency_interco/AddressDecoder_Resp.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cluster_interconnect/rtl/low_latency_interco/TestAndSet.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cluster_interconnect/rtl/low_latency_interco/RequestBlock2CH.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cluster_interconnect/rtl/low_latency_interco/RequestBlock1CH.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cluster_interconnect/rtl/low_latency_interco/FanInPrimitive_Resp.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cluster_interconnect/rtl/low_latency_interco/ResponseTree.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cluster_interconnect/rtl/low_latency_interco/ResponseBlock.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cluster_interconnect/rtl/low_latency_interco/AddressDecoder_Req.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cluster_interconnect/rtl/low_latency_interco/XBAR_TCDM.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cluster_interconnect/rtl/low_latency_interco/XBAR_TCDM_WRAPPER.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cluster_interconnect/rtl/low_latency_interco/TCDM_PIPE_REQ.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cluster_interconnect/rtl/low_latency_interco/TCDM_PIPE_RESP.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cluster_interconnect/rtl/low_latency_interco/grant_mask.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cluster_interconnect/rtl/low_latency_interco/priority_Flag_Req.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cluster_interconnect/rtl/peripheral_interco/AddressDecoder_PE_Req.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cluster_interconnect/rtl/peripheral_interco/AddressDecoder_Resp_PE.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cluster_interconnect/rtl/peripheral_interco/ArbitrationTree_PE.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cluster_interconnect/rtl/peripheral_interco/FanInPrimitive_Req_PE.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cluster_interconnect/rtl/peripheral_interco/RR_Flag_Req_PE.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cluster_interconnect/rtl/peripheral_interco/MUX2_REQ_PE.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cluster_interconnect/rtl/peripheral_interco/FanInPrimitive_PE_Resp.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cluster_interconnect/rtl/peripheral_interco/RequestBlock1CH_PE.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cluster_interconnect/rtl/peripheral_interco/RequestBlock2CH_PE.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cluster_interconnect/rtl/peripheral_interco/ResponseBlock_PE.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cluster_interconnect/rtl/peripheral_interco/ResponseTree_PE.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cluster_interconnect/rtl/peripheral_interco/XBAR_PE.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cluster_interconnect/rtl/tcdm_interconnect/tcdm_interconnect_pkg.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cluster_interconnect/rtl/tcdm_interconnect/addr_dec_resp_mux.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cluster_interconnect/rtl/tcdm_interconnect/amo_shim.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cluster_interconnect/rtl/tcdm_interconnect/xbar.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cluster_interconnect/rtl/tcdm_interconnect/clos_net.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cluster_interconnect/rtl/tcdm_interconnect/bfly_net.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cluster_interconnect/rtl/tcdm_interconnect/tcdm_interconnect.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/adv_dbg_if/rtl/adbg_axi_biu.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/adv_dbg_if/rtl/adbg_axi_module.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/adv_dbg_if/rtl/adbg_lint_biu.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/adv_dbg_if/rtl/adbg_lint_module.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/adv_dbg_if/rtl/adbg_crc32.v \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/adv_dbg_if/rtl/adbg_or1k_biu.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/adv_dbg_if/rtl/adbg_or1k_module.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/adv_dbg_if/rtl/adbg_or1k_status_reg.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/adv_dbg_if/rtl/adbg_top.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/adv_dbg_if/rtl/bytefifo.v \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/adv_dbg_if/rtl/syncflop.v \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/adv_dbg_if/rtl/syncreg.v \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/adv_dbg_if/rtl/adbg_tap_top.v \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/adv_dbg_if/rtl/adv_dbg_if.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/adv_dbg_if/rtl/adbg_axionly_top.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/adv_dbg_if/rtl/adbg_lintonly_top.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/apb/apb2per/apb2per.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/apb/apb_adv_timer/./rtl/adv_timer_apb_if.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/apb/apb_adv_timer/./rtl/comparator.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/apb/apb_adv_timer/./rtl/input_stage.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/apb/apb_adv_timer/./rtl/lut_4x4.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/apb/apb_adv_timer/./rtl/out_filter.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/apb/apb_adv_timer/./rtl/timer_cntrl.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/apb/apb_adv_timer/./rtl/up_down_counter.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/apb/apb_adv_timer/./rtl/prescaler.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/apb/apb_adv_timer/./rtl/timer_module.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/apb/apb_adv_timer/./rtl/apb_adv_timer.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/apb/apb_fll_if/src/fll_intf.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/apb/apb_fll_if/src/apb_fll_if.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/apb/apb_fll_if/src/apb_to_fll.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/apb/apb_gpio/./rtl/apb_gpio.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/apb/apb_node/src/apb_node.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/apb/apb_node/src/apb_node_wrap.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/apb_interrupt_cntrl/apb_interrupt_cntrl.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/axi/axi/src/axi_pkg.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/axi/axi/src/axi_intf.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/axi/axi/src/axi_atop_filter.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/axi/axi/src/axi_burst_splitter.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/axi/axi/src/axi_cdc_dst.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/axi/axi/src/axi_cdc_src.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/axi/axi/src/axi_cut.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/axi/axi/src/axi_delayer.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/axi/axi/src/axi_demux.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/axi/axi/src/axi_dw_downsizer.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/axi/axi/src/axi_dw_upsizer.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/axi/axi/src/axi_id_prepend.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/axi/axi/src/axi_isolate.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/axi/axi/src/axi_join.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/axi/axi/src/axi_lite_demux.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/axi/axi/src/axi_lite_join.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/axi/axi/src/axi_lite_mailbox.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/axi/axi/src/axi_lite_mux.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/axi/axi/src/axi_lite_regs.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/axi/axi/src/axi_lite_to_apb.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/axi/axi/src/axi_lite_to_axi.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/axi/axi/src/axi_modify_address.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/axi/axi/src/axi_mux.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/axi/axi/src/axi_serializer.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/axi/axi/src/axi_cdc.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/axi/axi/src/axi_err_slv.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/axi/axi/src/axi_dw_converter.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/axi/axi/src/axi_multicut.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/axi/axi/src/axi_to_axi_lite.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/axi/axi/src/axi_lite_xbar.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/axi/axi/src/axi_xbar.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/axi/axi_slice/src/axi_single_slice.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/axi/axi_slice/src/axi_ar_buffer.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/axi/axi_slice/src/axi_aw_buffer.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/axi/axi_slice/src/axi_b_buffer.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/axi/axi_slice/src/axi_r_buffer.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/axi/axi_slice/src/axi_slice.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/axi/axi_slice/src/axi_w_buffer.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/axi/axi_slice/src/axi_slice_wrap.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/timer_unit/./rtl/apb_timer_unit.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/timer_unit/./rtl/timer_unit.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/timer_unit/./rtl/timer_unit_counter.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/timer_unit/./rtl/timer_unit_counter_presc.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/fpu_div_sqrt_mvp/hdl/defs_div_sqrt_mvp.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/fpu_div_sqrt_mvp/hdl/control_mvp.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/fpu_div_sqrt_mvp/hdl/div_sqrt_mvp_wrapper.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/fpu_div_sqrt_mvp/hdl/div_sqrt_top_mvp.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/fpu_div_sqrt_mvp/hdl/iteration_div_sqrt_mvp.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/fpu_div_sqrt_mvp/hdl/norm_div_sqrt_mvp.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/fpu_div_sqrt_mvp/hdl/nrbd_nrsc_mvp.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/fpu_div_sqrt_mvp/hdl/preprocess_mvp.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/fpnew/src/fpnew_pkg.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/fpnew/src/fpnew_cast_multi.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/fpnew/src/fpnew_classifier.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/fpnew/src/fpnew_divsqrt_multi.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/fpnew/src/fpnew_fma.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/fpnew/src/fpnew_fma_multi.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/fpnew/src/fpnew_noncomp.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/fpnew/src/fpnew_opgroup_block.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/fpnew/src/fpnew_opgroup_fmt_slice.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/fpnew/src/fpnew_opgroup_multifmt_slice.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/fpnew/src/fpnew_rounding.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/fpnew/src/fpnew_top.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/jtag_pulp/src/bscell.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/jtag_pulp/src/jtag_axi_wrap.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/jtag_pulp/src/jtag_enable.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/jtag_pulp/src/jtag_enable_synch.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/jtag_pulp/src/jtagreg.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/jtag_pulp/src/jtag_rst_synch.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/jtag_pulp/src/jtag_sync.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/jtag_pulp/src/tap_top.v \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cv32e40p/./rtl/register_file_test_wrap.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cv32e40p/./rtl/riscv_register_file_latch.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cv32e40p/./rtl/include/apu_core_package.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cv32e40p/./rtl/include/riscv_defines.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cv32e40p/./rtl/include/riscv_tracer_defines.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cv32e40p/./rtl/riscv_alu.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cv32e40p/./rtl/riscv_alu_basic.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cv32e40p/./rtl/riscv_alu_div.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cv32e40p/./rtl/riscv_compressed_decoder.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cv32e40p/./rtl/riscv_controller.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cv32e40p/./rtl/riscv_cs_registers.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cv32e40p/./rtl/riscv_decoder.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cv32e40p/./rtl/riscv_int_controller.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cv32e40p/./rtl/riscv_ex_stage.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cv32e40p/./rtl/riscv_hwloop_controller.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cv32e40p/./rtl/riscv_hwloop_regs.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cv32e40p/./rtl/riscv_id_stage.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cv32e40p/./rtl/riscv_if_stage.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cv32e40p/./rtl/riscv_load_store_unit.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cv32e40p/./rtl/riscv_mult.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cv32e40p/./rtl/riscv_prefetch_buffer.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cv32e40p/./rtl/riscv_prefetch_L0_buffer.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cv32e40p/./rtl/riscv_core.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cv32e40p/./rtl/riscv_apu_disp.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cv32e40p/./rtl/riscv_fetch_fifo.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cv32e40p/./rtl/riscv_L0_buffer.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cv32e40p/./rtl/riscv_pmp.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cv32e40p/./rtl/riscv_tracer.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cv32e40p/tb/tb_riscv/include/perturbation_defines.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cv32e40p/tb/tb_riscv/riscv_simchecker.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cv32e40p/tb/tb_riscv/tb_riscv_core.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cv32e40p/tb/tb_riscv/riscv_perturbation.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cv32e40p/tb/tb_riscv/riscv_random_interrupt_generator.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/cv32e40p/tb/tb_riscv/riscv_random_stall.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/ibex/rtl/ibex_pkg.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/ibex/rtl/ibex_register_file_ff.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_assert.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/ibex/rtl/ibex_alu.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/ibex/rtl/ibex_compressed_decoder.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/ibex/rtl/ibex_controller.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/ibex/rtl/ibex_counter.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/ibex/rtl/ibex_csr.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/ibex/rtl/ibex_decoder.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/ibex/rtl/ibex_fetch_fifo.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/ibex/rtl/ibex_load_store_unit.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/ibex/rtl/ibex_multdiv_fast.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/ibex/rtl/ibex_multdiv_slow.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/ibex/rtl/ibex_pmp.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/ibex/rtl/ibex_wb_stage.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/ibex/rtl/ibex_cs_registers.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/ibex/rtl/ibex_ex_block.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/ibex/rtl/ibex_id_stage.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/ibex/rtl/ibex_prefetch_buffer.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/ibex/rtl/ibex_if_stage.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/ibex/rtl/ibex_core.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/ibex/rtl/ibex_pkg.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/ibex/rtl/ibex_tracer_pkg.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/ibex/rtl/ibex_tracer.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/ibex/rtl/ibex_core_tracing.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/ibex/rtl/ibex_register_file_latch.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/scm/latch_scm/register_file_1r_1w_test_wrap.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/scm/latch_scm/register_file_1w_64b_multi_port_read_32b_1row.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/scm/latch_scm/register_file_1w_multi_port_read_1row.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/scm/latch_scm/register_file_1r_1w_all.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/scm/latch_scm/register_file_1r_1w_all_test_wrap.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/scm/latch_scm/register_file_1r_1w_be.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/scm/latch_scm/register_file_1r_1w.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/scm/latch_scm/register_file_1r_1w_1row.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/scm/latch_scm/register_file_1w_128b_multi_port_read_32b.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/scm/latch_scm/register_file_1w_64b_multi_port_read_32b.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/scm/latch_scm/register_file_1w_64b_1r_32b.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/scm/latch_scm/register_file_1w_multi_port_read_be.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/scm/latch_scm/register_file_1w_multi_port_read.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/scm/latch_scm/register_file_2r_1w_asymm.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/scm/latch_scm/register_file_2r_1w_asymm_test_wrap.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/scm/latch_scm/register_file_2r_2w.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/scm/latch_scm/register_file_3r_2w.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/scm/latch_scm/register_file_3r_2w_be.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/scm/latch_scm/register_file_multi_way_1w_64b_multi_port_read_32b.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/scm/latch_scm/register_file_multi_way_1w_multi_port_read.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/tech_cells_generic/src/deprecated/cluster_clk_cells.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/tech_cells_generic/src/deprecated/cluster_pwr_cells.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/tech_cells_generic/src/deprecated/generic_memory.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/tech_cells_generic/src/deprecated/generic_rom.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/tech_cells_generic/src/deprecated/pad_functional.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/tech_cells_generic/src/deprecated/pulp_buffer.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/tech_cells_generic/src/deprecated/pulp_clk_cells.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/tech_cells_generic/src/deprecated/pulp_pwr_cells.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/tech_cells_generic/src/rtl/tc_clk.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/tech_cells_generic/src/rtl/tc_sram.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/tech_cells_generic/src/tc_pwr.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/tech_cells_generic/src/deprecated/pulp_clock_gating_async.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma/udma_core/rtl/common/io_clk_gen.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma/udma_core/rtl/common/io_event_counter.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma/udma_core/rtl/common/io_generic_fifo.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma/udma_core/rtl/common/io_shiftreg.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma/udma_core/rtl/common/udma_apb_if.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma/udma_core/rtl/common/udma_clk_div_cnt.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma/udma_core/rtl/common/udma_ctrl.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma/udma_core/rtl/common/udma_dc_fifo.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma/udma_core/rtl/core/udma_arbiter.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma/udma_core/rtl/core/udma_ch_addrgen.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma/udma_core/rtl/common/io_tx_fifo.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma/udma_core/rtl/common/io_tx_fifo_dc.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma/udma_core/rtl/common/io_tx_fifo_mark.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma/udma_core/rtl/common/udma_clkgen.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma/udma_core/rtl/core/udma_tx_channels.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma/udma_core/rtl/core/udma_stream_unit.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma/udma_core/rtl/core/udma_rx_channels.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma/udma_core/rtl/core/udma_core.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma/udma_uart/rtl/udma_uart_reg_if.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma/udma_uart/rtl/udma_uart_rx.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma/udma_uart/rtl/udma_uart_tx.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma/udma_uart/rtl/udma_uart_top.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma/udma_i2c/rtl/udma_i2c_reg_if.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma/udma_i2c/rtl/udma_i2c_bus_ctrl.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma/udma_i2c/rtl/udma_i2c_control.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma/udma_i2c/rtl/udma_i2c_top.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma/udma_i2s/rtl/cic_comb.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma/udma_i2s/rtl/cic_integrator.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma/udma_i2s/rtl/i2s_clk_gen.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma/udma_i2s/rtl/i2s_rx_channel.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma/udma_i2s/rtl/i2s_tx_channel.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma/udma_i2s/rtl/i2s_ws_gen.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma/udma_i2s/rtl/udma_i2s_reg_if.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma/udma_i2s/rtl/cic_top.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma/udma_i2s/rtl/i2s_clkws_gen.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma/udma_i2s/rtl/pdm_top.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma/udma_i2s/rtl/i2s_txrx.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma/udma_i2s/rtl/udma_i2s_top.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma/udma_qspi/rtl/udma_spim_reg_if.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma/udma_qspi/rtl/udma_spim_ctrl.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma/udma_qspi/rtl/udma_spim_txrx.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma/udma_qspi/rtl/udma_spim_top.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma/udma_sdio/rtl/sdio_crc7.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma/udma_sdio/rtl/sdio_crc16.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma/udma_sdio/rtl/udma_sdio_reg_if.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma/udma_sdio/rtl/sdio_txrx_cmd.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma/udma_sdio/rtl/sdio_txrx_data.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma/udma_sdio/rtl/sdio_txrx.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma/udma_sdio/rtl/udma_sdio_top.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma/udma_camera/rtl/camera_reg_if.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma/udma_camera/rtl/camera_if.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma/udma_filter/rtl/udma_filter_au.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma/udma_filter/rtl/udma_filter_bincu.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma/udma_filter/rtl/udma_filter_reg_if.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma/udma_filter/rtl/udma_filter_rx_dataout.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma/udma_filter/rtl/udma_filter_tx_datafetch.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma/udma_filter/rtl/udma_filter.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma/udma_external_per/rtl/udma_external_per_reg_if.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma/udma_external_per/rtl/udma_traffic_gen_rx.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma/udma_external_per/rtl/udma_traffic_gen_tx.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma/udma_external_per/rtl/udma_external_per_top.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma/udma_external_per/rtl/udma_external_per_wrapper.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma_hyper/udma-hyperbus/src/cdc_fifo_gray_hyper.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma_hyper/udma-hyperbus/src/graycode_hyper.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma_hyper/udma-hyperbus/src/clock_diff_out.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma_hyper/udma-hyperbus/src/clk_gen_hyper.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma_hyper/udma-hyperbus/src/onehot_to_bin_hyper.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma_hyper/udma-hyperbus/src/ddr_out.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma_hyper/udma-hyperbus/src/hyperbus_delay_line.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma_hyper/udma-hyperbus/src/read_clk_rwds.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma_hyper/udma-hyperbus/src/hyperbus_phy.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma_hyper/udma-hyperbus/src/cmd_addr_gen.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma_hyper/udma-hyperbus/src/ddr_in.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma_hyper/udma-hyperbus/src/udma_hyper_reg_if_common.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma_hyper/udma-hyperbus/src/udma_hyper_reg_if_mulid.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma_hyper/udma-hyperbus/src/udma_rxbuffer.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma_hyper/udma-hyperbus/src/udma_txbuffer.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma_hyper/udma-hyperbus/src/udma_hyper_ctrl.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma_hyper/udma-hyperbus/src/udma_hyperbus_mulid.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma_hyper/udma-hyperbus/src/hyper_unpack.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma_hyper/udma-hyperbus/src/udma_cfg_outbuff.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma_hyper/udma-hyperbus/src/hyperbus_mux_generic.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma_hyper/udma-hyperbus/src/hyper_twd_trans_spliter.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma_hyper/udma-hyperbus/src/hyper_rr_flag_req.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma_hyper/udma-hyperbus/src/hyper_arbiter.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma_hyper/udma-hyperbus/src/hyper_arb_primitive.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma_hyper/udma-hyperbus/src/io_generic_fifo_hyper.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma_hyper/udma-hyperbus/src/udma_dc_fifo_hyper.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma_hyper/udma-hyperbus/src/dc_token_ring_fifo_din_hyper.v \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma_hyper/udma-hyperbus/src/dc_token_ring_fifo_dout_hyper.v \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma_hyper/udma-hyperbus/src/dc_token_ring_hyper.v \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma_hyper/udma-hyperbus/src/dc_data_buffer_hyper.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma_hyper/udma-hyperbus/src/dc_full_detector_hyper.v \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma_hyper/udma-hyperbus/src/dc_synchronizer_hyper.v \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma_hyper/udma-hyperbus/src/udma_cmd_queue.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma_hyper/udma-hyperbus/src/udma_hyper_busy.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma_hyper/udma-hyperbus/src/udma_hyper_busy_phy.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/udma_hyper/udma-hyperbus/src/udma_hyper_top.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/hwpe-ctrl/rtl/hwpe_ctrl_package.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/hwpe-ctrl/rtl/hwpe_ctrl_interfaces.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/hwpe-ctrl/rtl/hwpe_ctrl_regfile.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/hwpe-ctrl/rtl/hwpe_ctrl_regfile_latch.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/hwpe-ctrl/rtl/hwpe_ctrl_regfile_latch_test_wrap.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/hwpe-ctrl/rtl/hwpe_ctrl_slave.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/hwpe-ctrl/rtl/hwpe_ctrl_seq_mult.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/hwpe-ctrl/rtl/hwpe_ctrl_uloop.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/hwpe-stream/rtl/hwpe_stream_package.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/hwpe-stream/rtl/hwpe_stream_interfaces.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/hwpe-stream/rtl/basic/hwpe_stream_assign.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/hwpe-stream/rtl/basic/hwpe_stream_mux_static.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/hwpe-stream/rtl/basic/hwpe_stream_demux_static.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/hwpe-stream/rtl/basic/hwpe_stream_buffer.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/hwpe-stream/rtl/basic/hwpe_stream_merge.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/hwpe-stream/rtl/basic/hwpe_stream_fence.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/hwpe-stream/rtl/basic/hwpe_stream_split.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/hwpe-stream/rtl/basic/hwpe_stream_serialize.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/hwpe-stream/rtl/basic/hwpe_stream_deserialize.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/hwpe-stream/rtl/fifo/hwpe_stream_fifo_earlystall_sidech.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/hwpe-stream/rtl/fifo/hwpe_stream_fifo_earlystall.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/hwpe-stream/rtl/fifo/hwpe_stream_fifo_scm.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/hwpe-stream/rtl/fifo/hwpe_stream_fifo_scm_test_wrap.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/hwpe-stream/rtl/fifo/hwpe_stream_fifo_sidech.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/hwpe-stream/rtl/fifo/hwpe_stream_fifo.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/hwpe-stream/rtl/fifo/hwpe_stream_fifo_ctrl.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/hwpe-stream/rtl/streamer/hwpe_stream_addressgen.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/hwpe-stream/rtl/streamer/hwpe_stream_addressgen_v2.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/hwpe-stream/rtl/streamer/hwpe_stream_addressgen_v3.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/hwpe-stream/rtl/streamer/hwpe_stream_strbgen.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/hwpe-stream/rtl/streamer/hwpe_stream_sink.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/hwpe-stream/rtl/streamer/hwpe_stream_sink_realign.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/hwpe-stream/rtl/streamer/hwpe_stream_source.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/hwpe-stream/rtl/streamer/hwpe_stream_source_realign.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/hwpe-stream/rtl/streamer/hwpe_stream_streamer_queue.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/hwpe-stream/rtl/tcdm/hwpe_stream_tcdm_fifo_load.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/hwpe-stream/rtl/tcdm/hwpe_stream_tcdm_fifo_load_sidech.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/hwpe-stream/rtl/tcdm/hwpe_stream_tcdm_fifo_store.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/hwpe-stream/rtl/tcdm/hwpe_stream_tcdm_fifo.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/hwpe-stream/rtl/tcdm/hwpe_stream_tcdm_assign.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/hwpe-stream/rtl/tcdm/hwpe_stream_tcdm_mux.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/hwpe-stream/rtl/tcdm/hwpe_stream_tcdm_mux_static.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/hwpe-stream/rtl/tcdm/hwpe_stream_tcdm_reorder.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/hwpe-stream/rtl/tcdm/hwpe_stream_tcdm_reorder_static.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/hwpe-mac-engine/rtl/mac_package.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/hwpe-mac-engine/rtl/mac_fsm.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/hwpe-mac-engine/rtl/mac_ctrl.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/hwpe-mac-engine/rtl/mac_streamer.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/hwpe-mac-engine/rtl/mac_engine.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/hwpe-mac-engine/rtl/mac_top.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/hwpe-mac-engine/wrap/mac_top_wrap.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/riscv-dbg/src/dm_pkg.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/riscv-dbg/debug_rom/debug_rom.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/riscv-dbg/debug_rom/debug_rom_one_scratch.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/riscv-dbg/src/dm_csrs.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/riscv-dbg/src/dm_mem.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/riscv-dbg/src/dm_top.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/riscv-dbg/src/dm_obi_top.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/riscv-dbg/src/dmi_cdc.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/riscv-dbg/src/dmi_jtag.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/riscv-dbg/src/dmi_jtag_tap.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/riscv-dbg/src/dm_sba.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/register_interface/src/reg_intf.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/register_interface/src/apb_to_reg.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/register_interface/src/axi_to_reg.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/register_interface/src/periph_to_reg.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/register_interface/src/reg_cdc.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/register_interface/src/reg_demux.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/register_interface/src/reg_mux.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/register_interface/src/reg_to_mem.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/register_interface/src/reg_uniform.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/register_interface/src/axi_lite_to_reg.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/register_interface/vendor/lowrisc_opentitan/src/prim_subreg.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/register_interface/vendor/lowrisc_opentitan/src/prim_subreg_arb.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/register_interface/vendor/lowrisc_opentitan/src/prim_subreg_ext.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/register_interface/vendor/lowrisc_opentitan/src/prim_subreg_shadow.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/register_interface/src/reg_test.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/pulp_soc/rtl/pulp_soc/pkg_soc_interconnect.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/pulp_soc/rtl/pulp_soc/axi64_2_lint32_wrap.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/pulp_soc/rtl/pulp_soc/lint_2_axi_wrap.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/pulp_soc/rtl/pulp_soc/contiguous_crossbar.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/pulp_soc/rtl/pulp_soc/interleaved_crossbar.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/pulp_soc/rtl/pulp_soc/tcdm_demux.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/pulp_soc/rtl/pulp_soc/boot_rom.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/pulp_soc/rtl/pulp_soc/l2_ram_multi_bank.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/pulp_soc/rtl/pulp_soc/lint_jtag_wrap.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/pulp_soc/rtl/pulp_soc/periph_bus_wrap.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/pulp_soc/rtl/pulp_soc/soc_clk_rst_gen.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/pulp_soc/rtl/pulp_soc/soc_event_arbiter.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/pulp_soc/rtl/pulp_soc/soc_event_generator.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/pulp_soc/rtl/pulp_soc/soc_event_queue.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/pulp_soc/rtl/pulp_soc/tcdm_error_slave.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/pulp_soc/rtl/pulp_soc/soc_interconnect.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/pulp_soc/rtl/pulp_soc/soc_interconnect_wrap.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/pulp_soc/rtl/pulp_soc/soc_peripherals.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/pulp_soc/rtl/pulp_soc/pulp_soc.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/pulp_soc/rtl/udma_subsystem/udma_subsystem.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/pulp_soc/rtl/fc/fc_demux.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/pulp_soc/rtl/fc/fc_subsystem.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/pulp_soc/rtl/fc/fc_hwpe.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/pulp_soc/rtl/components/apb_clkdiv.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/pulp_soc/rtl/components/apb_soc_ctrl.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/pulp_soc/rtl/components/memory_models.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/pulp_soc/rtl/components/pulp_interfaces.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/pulp_soc/rtl/components/glitch_free_clk_mux.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/pulp_soc/rtl/components/scm_2048x32.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/pulp_soc/rtl/components/scm_512x32.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/pulp_soc/rtl/components/tcdm_arbiter_2x1.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/pulp_soc/rtl/components/obi_pulp_adapter.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/pulp_soc/rtl/components/apb_intf.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/pulp_soc/rtl/components/glitch_free_clk_mux.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/pulp_soc/rtl/components/apb_dummy.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/pulp_soc/rtl/components/freq_meter.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/tbtools/dpi_models/dpi_models.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/tbtools/tb_driver/tb_driver.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/rtl/tb/riscv_pkg.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/rtl/tb/jtag_pkg.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/rtl/tb/pulp_tap_pkg.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/rtl/tb/tb_clk_gen.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/rtl/tb/tb_fs_handler.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/rtl/tb/dpi_models/dpi_models.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/rtl/tb/tb_driver/tb_driver.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/rtl/tb/tb_pulp.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/rtl/tb/SimJTAG.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/rtl/tb/SimDTM.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/rtl/vip/spi_master_padframe.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/rtl/vip/uart_tb_rx.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/rtl/vip/camera/cam_vip.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/rtl/pulpissimo/jtag_tap_top.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/rtl/pulpissimo/pad_control.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/rtl/pulpissimo/pad_frame.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/rtl/pulpissimo/safe_domain.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/rtl/pulpissimo/soc_domain.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/rtl/pulpissimo/rtc_date.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/rtl/pulpissimo/rtc_clock.sv \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/rtl/pulpissimo/pulpissimo.sv

analyze -vhdl08 \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/generic_FLL/fe/model/gf22_DCO_model.tc.vhd \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/generic_FLL/fe/model/gf22_FLL_model.vhd \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/generic_FLL/fe/rtl/FLLPkg.vhd \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/generic_FLL/fe/rtl/FLL_clk_divider.vhd \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/generic_FLL/fe/rtl/FLL_clk_period_quantizer.vhd \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/generic_FLL/fe/rtl/FLL_clock_gated.rtl.vhd \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/generic_FLL/fe/rtl/FLL_digital.vhd \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/generic_FLL/fe/rtl/FLL_dither_pattern_gen.vhd \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/generic_FLL/fe/rtl/FLL_glitchfree_clkdiv.vhd \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/generic_FLL/fe/rtl/FLL_glitchfree_clkmux.vhd \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/generic_FLL/fe/rtl/FLL_mux.rtl.vhd \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/generic_FLL/fe/rtl/FLL_loop_filter.vhd \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/generic_FLL/fe/rtl/FLL_reg.vhd \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/generic_FLL/fe/rtl/FLL_settling_monitor.vhd \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/generic_FLL/fe/rtl/FLL_synchroedge.vhd \
    /home/pedro.medeiros/Tools/riscv-formal-VeeR/cores/cv32e40p/ips/generic_FLL/fe/rtl/FLL_zerodelta.vhd

elaborate -top tb_pulp

clock clock

reset reset

prove -all
